version: '3'
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongodata:/data/db

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neopassword
    volumes:
      - neo4jdata:/data

volumes:
  pgdata:
  redisdata:
  mongodata:
  neo4jdata:
